sudo: required
services:
  - docker

before_install:
  - docker build -t giselebrito/docker-react -f Dockerfile.dev .

script:
  - docker run giselebrito/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "giselebrito-docker-react"
  env: "GiselebritoDockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-682055422744"
  bucket_path: "giselebrito-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"